name: movies_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-24.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.1.0
  build_runner: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
